name: pensopay_ios
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/pensopay/flutter_pensopay
repository: https://github.com/pensopay/flutter_pensopay

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PensopayIosPlugin